const jsonServer = require("json-server");

const server = jsonServer.create();

// Define your data directly in the code, simulating the db.json content
const db = {
  branches: [
    {
      id: 1,
      name: "ekbatan",
      title: "شعبه اکباتان",
      image:
        "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/info-1.jfif",
      phone_numberes: {
        mobile: "۰۲۱-۵۴۸۹۱۲۵۰-۵۱",
        desktop_1: "۰۲۱-۵۴۸۹۱۲۵۰",
        desktop_2: "۰۲۱-۵۴۸۹۱۲۵۱",
      },
      location: "شهرک اکباتان، فاز ۳، مجتمع تجاری کوروش، طبقه سوم",
      work_time: "همه‌روزه از ساعت ۱۲ الی ۲۳",
      special_foods: [
        {
          id: "1",
          title: "دلمه برگ کلم",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-1.jfif",
          main_price: "۲۲۰,۰۰۰",
          discount: "%۸",
          price: "۲۰۹,۰۰۰",
          score: "۵۲",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "2",
          title: "بادمجان شکم‌پر",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-2.jfif",
          main_price: "۱۵۰,۰۰۰",
          discount: "%۱۸",
          price: "۱۳۶,۰۰۰",
          score: "۳۲",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "3",
          title: "کالزونه اسفناج",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-3.jfif",
          main_price: "۱۹۰,۰۰۰",
          discount: "%۱۷",
          price: "۱۷۷,۰۰۰",
          score: "۶۲",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "4",
          title: "پیتزا قارچ",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-4.jfif",
          main_price: "۲۱۵,۰۰۰",
          discount: "%۲۵",
          price: "۱۷۵,۰۰۰",
          score: "۳۳",
          rate: "۳",
          isLiked: false,
        },
        {
          id: "5",
          title: "پاستا سبزیجات",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-5.jfif",
          main_price: "",
          discount: "",
          price: "۱۵۰,۰۰۰",
          score: "۵۰",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "16",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/s-1.jfif",
          title: "ساندویچ کتلت مخصوص",
          main_price: "۲۳۰٬۰۰۰",
          discount: "%۱۸",
          price: "۲۰۵٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "17",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-f-3.jfif",
          title: "میرزا قاسمی",
          main_price: "۱۶۵٬۰۰۰",
          discount: "%۱۰",
          price: "۱۴۲٬۵۰۰ ",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
      ],
      famous_foods: [
        {
          id: "6",
          title: "پنینی اسفناج",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-1.jfif",
          main_price: "۲۱۰,۰۰۰",
          discount: "%۱۵",
          price: "۱۹۰,۰۰۰",
          score: "۲۰",
          rate: "۳",
          isLiked: false,
        },
        {
          id: "7",
          title: "پیتزا پپرونی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-2.jfif",
          main_price: "",
          discount: "",
          price: "۱۰۰,۰۰۰",
          score: "۵۱",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "8",
          title: "راتاتویی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-3.jfif",
          main_price: "۱۸۰,۰۰۰",
          discount: "%۴۵",
          price: "۹۵,۰۰۰",
          score: "۴۳",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "9",
          title: "بورانی بادمجان",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-4.jfif",
          main_price: "۱۷۰,۰۰۰",
          discount: "%۲۲",
          price: "۱۴۸,۰۰۰",
          score: "۷۵",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "10",
          title: "پاکورا گیاهی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-5.jfif",
          main_price: "۱۷۵,۰۰۰",
          discount: "%۲۰",
          price: "۱۵۰,۰۰۰",
          score: "۸۰",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "18",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/s-2.jfif",
          title: "ساندویچ سوسیس کوکتل",
          main_price: "۲۰۵٬۰۰۰",
          discount: "%۳۵",
          price: "۱۶۵٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "19",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-f-5.jfif",
          title: "فلافل",
          main_price: "",
          discount: "",
          price: "۸۰٬۰۰۰",
          rate: "3",
          score: "۷۲",
          isLiked: false,
        },
      ],
      foreign_foods: [
        {
          id: "11",
          title: "سوشی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-1.jfif",
          main_price: "۱۰۰,۰۰۰",
          discount: "%۱۵",
          price: "۸۵,۰۰۰",
          score: "۷۰",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "12",
          title: "راتاتویی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-2.jfif",
          main_price: "۱۸۰,۰۰۰",
          discount: "%۴۵",
          price: "۹۵,۰۰۰",
          score: "۴۳",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "13",
          title: "پاکورا سبزیجات",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-3.jfif",
          main_price: "۱۲۵,۰۰۰",
          discount: "%۸",
          price: "۱۱۰,۰۰۰",
          score: "۷۵",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "14",
          title: "لازانیا",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-4.jfif",
          main_price: "",
          discount: "",
          price: "۱۵۰,۰۰۰",
          score: "۴۸",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "15",
          title: "سالاد خانگی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-5.jfif",
          main_price: "۱۷۵,۰۰۰",
          discount: "%۲۰",
          price: "۱۵۰,۰۰۰",
          score: "۵۹",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "20",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-6.jfif",
          title: "پیتزا اسفناج",
          main_price: "۲۸۰٬۰۰۰",
          discount: "%۱۰",
          price: "۲۵۲٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "21",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/f-f-8.jfif",
          title: "پالاک پنیر ",
          main_price: "۲۰۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۸۰٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
      ],
      comments: [
        {
          id: "1",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-1.jfif",
          name: "آرزو محمدعلیزاده",
          date: "۲۲ اسفند ۱۴۰۱",
          description:
            "از با صفا بودن شعبه اکباتان هر چی بگم کم گفتم. بهترین غذاهای گیاهی عمرمو اینجا خوردم. از مدیریت شعبه اکباتان رستوران‌های ترخینه واقعا تشکر میکنم. ",
          rate: "۴",
        },
        {
          id: "2",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-2.jfif",
          name: "سردار وظیفه",
          date: "۱۴ اسفند ۱۴۰۱",
          description:
            "از با صفا بودن شعبه اکباتان هر چی بگم کم گفتم. بهترین غذاهای گیاهی عمرمو اینجا خوردم. از مدیریت شعبه اکباتان رستوران‌های ترخینه واقعا تشکر میکنم. ",
          rate: "۴",
        },
        {
          id: "3",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-3.jfif",
          name: "علی مضفری",
          date: "۵ اسفند ۱۴۰۱",
          description:
            "از با صفا بودن شعبه اکباتان هر چی بگم کم گفتم. بهترین غذاهای گیاهی عمرمو اینجا خوردم. از مدیریت شعبه اکباتان رستوران‌های ترخینه واقعا تشکر میکنم. ",
          rate: "۴",
        },
      ],
    },
    {
      id: 2,
      name: "chalos",
      title: "شعبه چالوس",
      image:
        "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/info-2.jfif",
      phone_numberes: {
        mobile: "۰۲۱-۵۴۸۹۱۲۵۲-۵۳",
        desktop_1: "۰۲۱-۵۴۸۹۱۲۵۲",
        desktop_2: "۰۲۱-۵۴۸۹۱۲۵۳",
      },
      location:
        "چالوس، خیابان ۱۷ شهریور، بعد کوچه کوروش، جنب داروخانه دکتر میلانی",
      work_time: "همه‌روزه از ساعت ۱۲ الی ۲۳",
      special_foods: [
        {
          id: "1",
          title: "پیتزا قارچ",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-4.jfif",
          main_price: "۲۱۵,۰۰۰",
          discount: "%۲۵",
          price: "۱۷۵,۰۰۰",
          score: "۳۳",
          rate: "۳",
          isLiked: false,
        },
        {
          id: "16",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/s-1.jfif",
          title: "ساندویچ کتلت مخصوص",
          main_price: "۲۳۰٬۰۰۰",
          discount: "%۱۸",
          price: "۲۰۵٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "2",
          title: "بادمجان شکم‌پر",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-2.jfif",
          main_price: "۱۵۰,۰۰۰",
          discount: "%۱۸",
          price: "۱۳۶,۰۰۰",
          score: "۳۲",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "3",
          title: "پاستا سبزیجات",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-5.jfif",
          main_price: "",
          discount: "",
          price: "۱۵۰,۰۰۰",
          score: "۵۰",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "17",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-f-3.jfif",
          title: "میرزا قاسمی",
          main_price: "۱۶۵٬۰۰۰",
          discount: "%۱۰",
          price: "۱۴۲٬۵۰۰ ",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "4",
          title: "کالزونه اسفناج",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-3.jfif",
          main_price: "۱۹۰,۰۰۰",
          discount: "%۱۷",
          price: "۱۷۷,۰۰۰",
          score: "۶۲",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "5",
          title: "دلمه برگ کلم",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-1.jfif",
          main_price: "۲۲۰,۰۰۰",
          discount: "%۸",
          price: "۲۰۹,۰۰۰",
          score: "۵۲",
          rate: "۵",
          isLiked: false,
        },
      ],
      famous_foods: [
        {
          id: "19",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-f-5.jfif",
          title: "فلافل",
          main_price: "",
          discount: "",
          price: "۸۰٬۰۰۰",
          rate: "3",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "6",
          title: "راتاتویی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-3.jfif",
          main_price: "۱۸۰,۰۰۰",
          discount: "%۴۵",
          price: "۹۵,۰۰۰",
          score: "۴۳",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "7",
          title: "پیتزا پپرونی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-2.jfif",
          main_price: "",
          discount: "",
          price: "۱۰۰,۰۰۰",
          score: "۵۱",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "8",
          title: "پنینی اسفناج",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-1.jfif",
          main_price: "۲۱۰,۰۰۰",
          discount: "%۱۵",
          price: "۱۹۰,۰۰۰",
          score: "۲۰",
          rate: "۳",
          isLiked: false,
        },
        {
          id: "9",
          title: "پاکورا گیاهی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-5.jfif",
          main_price: "۱۷۵,۰۰۰",
          discount: "%۲۰",
          price: "۱۵۰,۰۰۰",
          score: "۸۰",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "18",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/s-2.jfif",
          title: "ساندویچ سوسیس کوکتل",
          main_price: "۲۰۵٬۰۰۰",
          discount: "%۳۵",
          price: "۱۶۵٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "10",
          title: "بورانی بادمجان",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-4.jfif",
          main_price: "۱۷۰,۰۰۰",
          discount: "%۲۲",
          price: "۱۴۸,۰۰۰",
          score: "۷۵",
          rate: "۵",
          isLiked: false,
        },
      ],
      foreign_foods: [
        {
          id: "11",
          title: "راتاتویی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-2.jfif",
          main_price: "۱۸۰,۰۰۰",
          discount: "%۴۵",
          price: "۹۵,۰۰۰",
          score: "۴۳",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "20",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-6.jfif",
          title: "پیتزا اسفناج",
          main_price: "۲۸۰٬۰۰۰",
          discount: "%۱۰",
          price: "۲۵۲٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "12",
          title: "سالاد خانگی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-5.jfif",
          main_price: "۱۷۵,۰۰۰",
          discount: "%۲۰",
          price: "۱۵۰,۰۰۰",
          score: "۵۹",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "13",
          title: "سوشی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-1.jfif",
          main_price: "۱۰۰,۰۰۰",
          discount: "%۱۵",
          price: "۸۵,۰۰۰",
          score: "۷۰",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "21",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/f-f-8.jfif",
          title: "پالاک پنیر ",
          main_price: "۲۰۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۸۰٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "14",
          title: "لازانیا",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-4.jfif",
          main_price: "",
          discount: "",
          price: "۱۵۰,۰۰۰",
          score: "۴۸",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "15",
          title: "پاکورا سبزیجات",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-3.jfif",
          main_price: "۱۲۵,۰۰۰",
          discount: "%۸",
          price: "۱۱۰,۰۰۰",
          score: "۷۵",
          rate: "۴",
          isLiked: false,
        },
      ],
      comments: [
        {
          id: "1",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-4.jfif",
          name: "محمدرضا رستمی",
          date: "۱۰ فروردین ۱۴۰۲",
          description:
            "منظره‌ی فوق‌العاده‌ای داره، مخصوصاً وقتی کنار پنجره می‌نشینی و صدای دریا میاد. کیفیت غذاها خیلی خوب بود، مخصوصاً ماهی و دوغ محلی‌شون.",
          rate: "۵",
        },
        {
          id: "2",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-5.jfif",
          name: "الناز کیانی",
          date: "۲۶ اردیبهشت ۱۴۰۲",
          description:
            "فضای رستوران واقعا آرامش‌بخشه. غذاها تازه و خوش‌طعم بودن ولی سرویس‌دهی کمی طول کشید.",
          rate: "۴",
        },
        {
          id: "3",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-6.jfif",
          name: "مهیار احمدی",
          date: "۱۲ خرداد ۱۴۰۲",
          description:
            "اولین بار بود اینجا غذا می‌خوردم. برخورد پرسنل عالی بود و فضای خانوادگی خوبی داشت.",
          rate: "۵",
        },
      ],
    },
    {
      id: 3,
      name: "aghdasiyeh",
      title: "شعبه اقدسیه",
      image:
        "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/info-3.jfif",
      phone_numberes: {
        mobile: "۰۲۱-۵۴۸۹۱۲۵۴-۵۵",
        desktop_1: "۰۲۱-۵۴۸۹۱۲۵۴",
        desktop_2: "۰۲۱-۵۴۸۹۱۲۵۵",
      },
      location: "خیابان اقدسیه ، نرسیده به میدان خیام، پلاک ۸",
      work_time: "همه‌روزه از ساعت ۱۲ الی ۲۳",
      special_foods: [
        {
          id: "17",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-f-3.jfif",
          title: "میرزا قاسمی",
          main_price: "۱۶۵٬۰۰۰",
          discount: "%۱۰",
          price: "۱۴۲٬۵۰۰ ",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "1",
          title: "بادمجان شکم‌پر",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-2.jfif",
          main_price: "۱۵۰,۰۰۰",
          discount: "%۱۸",
          price: "۱۳۶,۰۰۰",
          score: "۳۲",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "2",
          title: "پاستا سبزیجات",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-5.jfif",
          main_price: "",
          discount: "",
          price: "۱۵۰,۰۰۰",
          score: "۵۰",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "3",
          title: "کالزونه اسفناج",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-3.jfif",
          main_price: "۱۹۰,۰۰۰",
          discount: "%۱۷",
          price: "۱۷۷,۰۰۰",
          score: "۶۲",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "4",
          title: "دلمه برگ کلم",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-1.jfif",
          main_price: "۲۲۰,۰۰۰",
          discount: "%۸",
          price: "۲۰۹,۰۰۰",
          score: "۵۲",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "16",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/s-1.jfif",
          title: "ساندویچ کتلت مخصوص",
          main_price: "۲۳۰٬۰۰۰",
          discount: "%۱۸",
          price: "۲۰۵٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "5",
          title: "پیتزا قارچ",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-4.jfif",
          main_price: "۲۱۵,۰۰۰",
          discount: "%۲۵",
          price: "۱۷۵,۰۰۰",
          score: "۳۳",
          rate: "۳",
          isLiked: false,
        },
      ],
      famous_foods: [
        {
          id: "6",
          title: "بورانی بادمجان",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-4.jfif",
          main_price: "۱۷۰,۰۰۰",
          discount: "%۲۲",
          price: "۱۴۸,۰۰۰",
          score: "۷۵",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "7",
          title: "پیتزا پپرونی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-2.jfif",
          main_price: "",
          discount: "",
          price: "۱۰۰,۰۰۰",
          score: "۵۱",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "18",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/s-2.jfif",
          title: "ساندویچ سوسیس کوکتل",
          main_price: "۲۰۵٬۰۰۰",
          discount: "%۳۵",
          price: "۱۶۵٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "8",
          title: "پنینی اسفناج",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-1.jfif",
          main_price: "۲۱۰,۰۰۰",
          discount: "%۱۵",
          price: "۱۹۰,۰۰۰",
          score: "۲۰",
          rate: "۳",
          isLiked: false,
        },
        {
          id: "19",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-f-5.jfif",
          title: "فلافل",
          main_price: "",
          discount: "",
          price: "۸۰٬۰۰۰",
          rate: "3",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "9",
          title: "راتاتویی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-3.jfif",
          main_price: "۱۸۰,۰۰۰",
          discount: "%۴۵",
          price: "۹۵,۰۰۰",
          score: "۴۳",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "10",
          title: "پاکورا گیاهی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-5.jfif",
          main_price: "۱۷۵,۰۰۰",
          discount: "%۲۰",
          price: "۱۵۰,۰۰۰",
          score: "۸۰",
          rate: "۵",
          isLiked: false,
        },
      ],
      foreign_foods: [
        {
          id: "21",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/f-f-8.jfif",
          title: "پالاک پنیر ",
          main_price: "۲۰۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۸۰٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "11",
          title: "سوشی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-1.jfif",
          main_price: "۱۰۰,۰۰۰",
          discount: "%۱۵",
          price: "۸۵,۰۰۰",
          score: "۷۰",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "12",
          title: "پاکورا سبزیجات",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-3.jfif",
          main_price: "۱۲۵,۰۰۰",
          discount: "%۸",
          price: "۱۱۰,۰۰۰",
          score: "۷۵",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "13",
          title: "راتاتویی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-2.jfif",
          main_price: "۱۸۰,۰۰۰",
          discount: "%۴۵",
          price: "۹۵,۰۰۰",
          score: "۴۳",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "14",
          title: "سالاد خانگی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-5.jfif",
          main_price: "۱۷۵,۰۰۰",
          discount: "%۲۰",
          price: "۱۵۰,۰۰۰",
          score: "۵۹",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "20",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-6.jfif",
          title: "پیتزا اسفناج",
          main_price: "۲۸۰٬۰۰۰",
          discount: "%۱۰",
          price: "۲۵۲٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "15",
          title: "لازانیا",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-4.jfif",
          main_price: "",
          discount: "",
          price: "۱۵۰,۰۰۰",
          score: "۴۸",
          rate: "۵",
          isLiked: false,
        },
      ],
      comments: [
        {
          id: "1",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-7.jfif",
          name: "نگین سهرابی",
          date: "۵ تیر ۱۴۰۲",
          description:
            "فضای داخلی بسیار شیک و مدرن بود. غذاها هم با کیفیت بالا سرو شدن. حتما دوباره میام.",
          rate: "۵",
        },
        {
          id: "2",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-8.jfif",
          name: "مانی حسینی",
          date: "۱۸ مرداد ۱۴۰۲",
          description:
            "غذاها خوش‌طعم بودن ولی قیمت‌ها کمی بالا بود. در کل تجربه‌ی خوبی بود.",
          rate: "۴",
        },
        {
          id: "3",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-9.jfif",
          name: "فاطمه ذاکری",
          date: "۲۸ شهریور ۱۴۰۲",
          description:
            "محیط رستوران خیلی دلنشین بود. پیشنهاد می‌کنم سالاد مخصوص‌شون رو امتحان کنید، عالی بود.",
          rate: "۵",
        },
      ],
    },
    {
      id: 4,
      name: "vanak",
      title: "شعبه ونک",
      image:
        "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/info-4.jfif",
      phone_numberes: {
        mobile: "۰۲۱-۵۴۸۹۱۲۵۶-۵۷",
        desktop_1: "۰۲۱-۵۴۸۹۱۲۵۶",
        desktop_2: "۰۲۱-۵۴۸۹۱۲۵۷",
      },
      location: "میدان ونک، خیابان فردوسی، نبش کوچه نیلوفر، پلاک ۲۶",
      work_time: "همه‌روزه از ساعت ۱۲ الی ۲۳",
      special_foods: [
        {
          id: "1",
          title: "پیتزا قارچ",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-4.jfif",
          main_price: "۲۱۵,۰۰۰",
          discount: "%۲۵",
          price: "۱۷۵,۰۰۰",
          score: "۳۳",
          rate: "۳",
          isLiked: false,
        },
        {
          id: "17",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-f-3.jfif",
          title: "میرزا قاسمی",
          main_price: "۱۶۵٬۰۰۰",
          discount: "%۱۰",
          price: "۱۴۲٬۵۰۰ ",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "2",
          title: "بادمجان شکم‌پر",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-2.jfif",
          main_price: "۱۵۰,۰۰۰",
          discount: "%۱۸",
          price: "۱۳۶,۰۰۰",
          score: "۳۲",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "3",
          title: "کالزونه اسفناج",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-3.jfif",
          main_price: "۱۹۰,۰۰۰",
          discount: "%۱۷",
          price: "۱۷۷,۰۰۰",
          score: "۶۲",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "4",
          title: "دلمه برگ کلم",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-1.jfif",
          main_price: "۲۲۰,۰۰۰",
          discount: "%۸",
          price: "۲۰۹,۰۰۰",
          score: "۵۲",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "5",
          title: "پاستا سبزیجات",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/s-f-5.jfif",
          main_price: "",
          discount: "",
          price: "۱۵۰,۰۰۰",
          score: "۵۰",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "16",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/s-1.jfif",
          title: "ساندویچ کتلت مخصوص",
          main_price: "۲۳۰٬۰۰۰",
          discount: "%۱۸",
          price: "۲۰۵٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
      ],
      famous_foods: [
        {
          id: "6",
          title: "پیتزا پپرونی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-2.jfif",
          main_price: "",
          discount: "",
          price: "۱۰۰,۰۰۰",
          score: "۵۱",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "7",
          title: "پنینی اسفناج",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-1.jfif",
          main_price: "۲۱۰,۰۰۰",
          discount: "%۱۵",
          price: "۱۹۰,۰۰۰",
          score: "۲۰",
          rate: "۳",
          isLiked: false,
        },
        {
          id: "19",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-f-5.jfif",
          title: "فلافل",
          main_price: "",
          discount: "",
          price: "۸۰٬۰۰۰",
          rate: "3",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "8",
          title: "راتاتویی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-3.jfif",
          main_price: "۱۸۰,۰۰۰",
          discount: "%۴۵",
          price: "۹۵,۰۰۰",
          score: "۴۳",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "9",
          title: "پاکورا گیاهی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-5.jfif",
          main_price: "۱۷۵,۰۰۰",
          discount: "%۲۰",
          price: "۱۵۰,۰۰۰",
          score: "۸۰",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "10",
          title: "بورانی بادمجان",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/p-f-4.jfif",
          main_price: "۱۷۰,۰۰۰",
          discount: "%۲۲",
          price: "۱۴۸,۰۰۰",
          score: "۷۵",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "18",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/s-2.jfif",
          title: "ساندویچ سوسیس کوکتل",
          main_price: "۲۰۵٬۰۰۰",
          discount: "%۳۵",
          price: "۱۶۵٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
      ],
      foreign_foods: [
        {
          id: "11",
          title: "پاکورا سبزیجات",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-3.jfif",
          main_price: "۱۲۵,۰۰۰",
          discount: "%۸",
          price: "۱۱۰,۰۰۰",
          score: "۷۵",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "12",
          title: "سوشی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-1.jfif",
          main_price: "۱۰۰,۰۰۰",
          discount: "%۱۵",
          price: "۸۵,۰۰۰",
          score: "۷۰",
          rate: "۴",
          isLiked: false,
        },
        {
          id: "13",
          title: "لازانیا",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-4.jfif",
          main_price: "",
          discount: "",
          price: "۱۵۰,۰۰۰",
          score: "۴۸",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "20",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/p-6.jfif",
          title: "پیتزا اسفناج",
          main_price: "۲۸۰٬۰۰۰",
          discount: "%۱۰",
          price: "۲۵۲٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "14",
          title: "سالاد خانگی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-5.jfif",
          main_price: "۱۷۵,۰۰۰",
          discount: "%۲۰",
          price: "۱۵۰,۰۰۰",
          score: "۵۹",
          rate: "۵",
          isLiked: false,
        },
        {
          id: "21",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/f-f-8.jfif",
          title: "پالاک پنیر ",
          main_price: "۲۰۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۸۰٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "15",
          title: "راتاتویی",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/f-f-2.jfif",
          main_price: "۱۸۰,۰۰۰",
          discount: "%۴۵",
          price: "۹۵,۰۰۰",
          score: "۴۳",
          rate: "۴",
          isLiked: false,
        },
      ],
      comments: [
        {
          id: "1",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-10.jfif",
          name: "سحر مرادی",
          date: "۱۵ مهر ۱۴۰۲",
          description:
            "شعبه ونک همیشه شلوغه ولی ارزش صبر کردن داره. غذاها با کیفیت بالا و سرویس سریع بود.",
          rate: "۵",
        },
        {
          id: "2",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-11.jfif",
          name: "امیر نادری",
          date: "۳۰ آبان ۱۴۰۲",
          description:
            "فضای بیرونی خیلی قشنگه مخصوصاً شب‌ها. فقط میزها کمی به هم نزدیک بودن.",
          rate: "۴",
        },
        {
          id: "3",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/branches/c-12.jfif",
          name: "پریسا یزدی",
          date: "۲۴ آذر ۱۴۰۲",
          description:
            "یکی از بهترین تجربه‌های غذاخوردنم بود. کارکنان خیلی مؤدب بودن و پاستاها فوق‌العاده.",
          rate: "۵",
        },
      ],
    },
  ],
  menu: [
    {
      id: 1,
      name: "main_dish",
      persian_foods: [
        {
          id: "1",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-1.jfif",
          title: "کوفته برنجی",
          detail: "برنج سبزی کوفته لپه آرد نخودچی، گردو و زرشک و آلو پیاز",
          main_price: "۱۸۰٬۰۰۰",
          discount: "%۳۵",
          price: "۱۴۵٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "2",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-2.jfif",
          title: "کشک بادمجان",
          detail: "بادمجان، کشک، نعناع خشک، مغز گردو، سیر، پیاز",
          main_price: "",
          discount: "",
          price: "۹۵٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "3",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-3.jfif",
          title: "میرزا قاسمی",
          detail: "بادمجان، گوجه فرنگی، تخم مرغ، سیر، رب گوجه فرنگی",
          main_price: "۱۶۵٬۰۰۰",
          discount: "%۱۰",
          price: "۱۴۲٬۵۰۰ ",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "4",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-4.jfif",
          title: "باقلاقاتوق",
          detail: "پاچ باقلا، شوید خشک، کره، سیر، تخم مرغ",
          main_price: "۲۰۵٬۰۰۰",
          discount: "%۳۰",
          price: "۱۸۰٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "5",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-5.jfif",
          title: "فلافل",
          detail: "نخود، پیاز، تخم گشنیز، سیر، جعفری، سیب زمینی",
          main_price: "",
          discount: "",
          price: "۸۰٬۰۰۰",
          rate: "3",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "6",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-6.jfif",
          title: "کله جوش",
          detail: "کشک، گردو، پیاز، نعناع خشک",
          main_price: "۲۱۰٬۰۰۰",
          discount: "%۵",
          price: "۲۰۳٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "7",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-7.jfif",
          title: "بورانی بادمجان",
          detail: "بادمجان قلمی، ماست چکیده، سیر، روغن زیتون، مغز گردو",
          main_price: "۱۷۰٬۰۰۰",
          discount: "%۲۲",
          price: "۱۴۸٬۰۰۰ ",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "8",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-8.jfif",
          title: "بادمجان شکم‌پر",
          detail: "بادمجان، پیاز، گوجه فرنگی، سبزی خشک",
          main_price: "۱۵۰٬۰۰۰",
          discount: "%۱۸",
          price: "۱۳۶٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "9",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-9.jfif",
          title: "دلمه برگ کلم",
          detail: "کلم برگ، برنج، لپه پخته، پیاز، سبزی معطر، رب",
          main_price: "۲۲۰٬۰۰۰",
          discount: "%۸",
          price: "۲۲۰٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "10",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-10.jfif",
          title: "دلمه برگ مو",
          detail: "پیاز، برنج، لپه، سبزی دلمه، سرکه",
          main_price: "",
          discount: "",
          price: "۱۹۵٬۰۰۰ ",
          rate: "2",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "11",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-11.jfif",
          title: "کوکو سبزی",
          detail: "تخم مرغ، گردو، سیر، آرد، روغن مایع، سبزی‌ کوکویی",
          main_price: "۳۰۰٬۰۰۰",
          discount: "%۱۰",
          price: "۲۷۰٬۰۰۰ ",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "12",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-f-12.jfif",
          title: "کوکو سیب‌زمینی و عدس",
          detail: "عدس، سیب زمینی، پیاز متوسط، تخم مرغ، پودر سیر، آرد سوخاری",
          main_price: "۱۳۵٬۰۰۰",
          discount: "%۲۰",
          price: "۱۰۵٬۰۰۰",
          rate: "1",
          score: "۷۲",
          isLiked: false,
        },
      ],
      foreign_foods: [
        {
          id: "13",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/f-f-1.jfif",
          title: "پاستا سبزیجات",
          detail: "پاستا، قارچ، گوجه، کدوی خوردشده، پیاز خلالی‌شده",
          main_price: "۱۷۵٬۰۰۰",
          discount: "%۲۰",
          price: "۱۴۰٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "14",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/f-f-2.jfif",
          title: "پاستا بلونز",
          detail:
            "اسپاگتی، گوشت چرخ کرده، هویج، ساقه کرفس، گوجه فرنگی، سیر، پیاز، پنیر پارمزان، روغن زیتون",
          main_price: "۱۷۰٬۰۰۰",
          discount: "%۱۲",
          price: "۱۶۰٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "15",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/f-f-3.jfif",
          title: "راتاتویی",
          detail:
            "بادمجان، گوجه فرنگی، کدو سبز، پیاز، رب گوجه فرنگی، روغن زیتون، پنیر پارمزان",
          main_price: "۱۸۰٬۰۰۰",
          discount: "%۴۵",
          price: "۹۵٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "16",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/f-f-4.jfif",
          title: "لازانیا",
          detail:
            "لازانیا، قارچ، ریحان تازه، جعفری تازه، گوجه فرنگی، پنیر پیتزا، بادمجان",
          main_price: "",
          discount: "",
          price: "۱۵۰٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "17",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/f-f-5.jfif",
          title: "سوشی",
          detail:
            "جلبک دریایی/ نوری، برنج کته، سرکه سفید (یا سرکه برنج)، شکر، نمک دریا",
          main_price: "۱۰۰٬۰۰۰",
          discount: "%۱۵",
          price: "۸۵٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "18",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/f-f-6.jfif",
          title: "پاکورا سبزیجات",
          detail: "گرام ماسالا، پودر کاری، سیر له شده، ،گشنیز خرد شده",
          main_price: "۱۲۵٬۰۰۰",
          discount: "%۸",
          price: "۱۱۰٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "19",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/f-f-7.jfif",
          title: "کالزونه اسفناج",
          detail:
            "اسفناج، قارچ، پنیر موزارلا یا پنیر پیتزا، پنیر ریکوتا یا پنیر خامه ای، پیاز، سیر، روغن زیتون",
          main_price: "۱۹۰٬۰۰۰",
          discount: "%۱۷",
          price: "۱۷۷٬۰۰۰ ",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "20",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/f-f-8.jfif",
          title: "پالاک پنیر ",
          detail: "پنیر، اسفناج، گوجه، پیاز، سیر ",
          main_price: "۲۰۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۸۰٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
      ],
      pizzas: [
        {
          id: "21",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-1.jfif",
          title: "پیتزا روکولا",
          detail:
            "اسفناج، سبزی روکولا، آرد، پودر مایه خمیر، روغن زیتون، خردل، سیر، پنیر موزارلا و پارمسان، گوجه گیلاسی ،سس فلفل سبز تند ",
          main_price: "۱۹۵٬۰۰۰",
          discount: "%۱۲",
          price: "۱۸۸٬۰۰۰ ",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "22",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-2.jfif",
          title: "پیتزا بادمجان و زیتون",
          detail:
            "بادمجان کوچک، روغن زیتون، پنیر موزارلا، پنیر پارمزان، برگ ریحان، گوجه فرنگی، سس گوجه فرنگی",
          main_price: "",
          discount: "",
          price: "۱۵۰٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "23",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-3.jfif",
          title: "پیتزا سبزیجات و خامه",
          detail:
            "نخود فرنگی پخته شده، ذرت نیم پز، فلفل دلمه‌ای رنگی، قارچ، سیر یا پیازچه خردشده",
          main_price: "۲۱۰٬۰۰۰",
          discount: "%۲۱",
          price: "۱۸۵٬۰۰۰ ",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "24",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-4.jfif",
          title: "پیتزا قارچ",
          detail:
            "قارچ، فلفل دلمه ای، رب گوجه فرنگی، پودر سیر، آویشن، مرزه، پنیر پیتزا گیاهی",
          main_price: "۲۱۵٬۰۰۰",
          discount: "%۲۵",
          price: "۱۷۵٬۰۰۰",
          rate: "3",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "25",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-5.jfif",
          title: "پیتزا پپرونی",
          detail:
            "تافو، فلفل قرمز خشک شده، پودر دانه‌های خردل، دانه رازیانه، پاپریکا دودی، پودر سیر، شکر نارگیل، پودر بادیان رومی",
          main_price: "",
          discount: "",
          price: "۱۰۰٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "26",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-6.jfif",
          title: "پیتزا اسفناج",
          detail: "اسفناج تازه، پیاز، سیر، پنیر پیتزا، قارچ",
          main_price: "۲۸۰٬۰۰۰",
          discount: "%۱۰",
          price: "۲۵۲٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "27",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-7.jfif",
          title: "پیتزا مارگاریتا",
          detail: "گوجه فرنگی، ریحان، سیر، پنیر پیتزا",
          main_price: "۱۶۵٬۰۰۰",
          discount: "%۱۳",
          price: "۱۴۷٬۰۰۰",
          rate: "2",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "28",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/p-8.jfif",
          title: "پیتزا پنیر",
          detail:
            "نان پیتزا، پنیر پیتزا، سس باربیکیو، گوجه فرنگی، سس کچاپ، سیر، روغن زیتون",
          main_price: "۱۲۵٬۰۰۰",
          discount: "%۱۶",
          price: "۱۰۵٬۰۰۰",
          rate: "3",
          score: "۷۲",
          isLiked: false,
        },
      ],
      sandwiches: [
        {
          id: "29",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/s-1.jfif",
          title: "ساندویچ کتلت مخصوص",
          detail:
            "سیب زمینی، لوبیا قرمز،  بلغور گندم، نعناع خشک، پودر زیره، پودر جوز هندی، گوجه فرنگی، روغن زیتون",
          main_price: "۲۳۰٬۰۰۰",
          discount: "%۱۸",
          price: "۲۰۵٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "30",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/s-2.jfif",
          title: "ساندویچ سوسیس کوکتل",
          detail: "سوسیس گیاهی، پیاز، سیب زمینی،  رب گوجه فرنگی",
          main_price: "۲۰۵٬۰۰۰",
          discount: "%۳۵",
          price: "۱۶۵٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "31",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/s-3.jfif",
          title: "ساندویچ کتلت کدو سبز",
          detail: "کدو سبز، هویج، سیب زمینی، پیاز",
          main_price: "",
          discount: "",
          price: "۱۴۵٬۰۰۰",
          rate: "5",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "32",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/main_dish/s-4.jfif",
          title: "پنینی اسفناج",
          detail:
            " قارچ، اسفناج، پیاز، پنیر پیتزا، خامه، پودر پاپریکا، گردو، سرکه بالزامیک، سس مایونز",
          main_price: "۲۱۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۹۰٬۰۰۰",
          rate: "3",
          score: "۷۲",
          isLiked: false,
        },
      ],
    },
    {
      id: 2,
      name: "appetizer",
      persian_appetizers: [
        {
          id: "1",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-1.jpg",
          title: "زیتون پرورده",
          detail: "زیتون سبز، گردو، رب انار، سیر، سبزی معطر",
          main_price: "۹۰٬۰۰۰",
          discount: "%۱۵",
          price: "۷۶٬۵۰۰",
          rate: "5",
          score: "۸۷",
          isLiked: false,
        },
        {
          id: "2",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-2.jpg",
          title: "ماست موسیر",
          detail: "ماست چکیده، موسیر خشک، نمک",
          main_price: "",
          discount: "",
          price: "۶۵٬۰۰۰",
          rate: "4",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "3",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-3.jpg",
          title: "ماست و خیار",
          detail: "ماست، خیار ریز خرد شده، نعناع خشک، گردو",
          main_price: "۷۵٬۰۰۰",
          discount: "%۱۰",
          price: "۶۷٬۵۰۰",
          rate: "5",
          score: "۸۹",
          isLiked: false,
        },
        {
          id: "4",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-4.jpg",
          title: "بورانی اسفناج",
          detail: "اسفناج پخته، ماست چکیده، سیر، نمک",
          main_price: "۹۵٬۰۰۰",
          discount: "%۲۰",
          price: "۷۶٬۰۰۰",
          rate: "4",
          score: "۷۸",
          isLiked: false,
        },
        {
          id: "5",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-5.jpg",
          title: "سیر ترشی",
          detail: "سیر، سرکه، نمک، شکر (ترش و کهنه)",
          main_price: "",
          discount: "",
          price: "۷۰٬۰۰۰",
          rate: "3",
          score: "۶۴",
          isLiked: false,
        },
        {
          id: "6",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-6.jpg",
          title: "ترشی مخلوط",
          detail: "گل کلم، هویج، فلفل سبز، خیار شور، سرکه طبیعی",
          main_price: "۸۵٬۰۰۰",
          discount: "%۵",
          price: "۸۰٬۷۵۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "7",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-7.jpg",
          title: "کشک و بادمجان لقمه‌ای",
          detail: "بادمجان سرخ شده، کشک، نعناع خشک، گردو، سیر",
          main_price: "۱۲۰٬۰۰۰",
          discount: "%۲۵",
          price: "۹۰٬۰۰۰",
          rate: "5",
          score: "۹۲",
          isLiked: false,
        },
        {
          id: "8",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-8.jpg",
          title: "ماست چکیده زعفرانی",
          detail: "ماست چکیده، زعفران دم‌کرده، خلال پسته، عسل",
          main_price: "۱۱۰٬۰۰۰",
          discount: "%۱۰",
          price: "۹۹٬۰۰۰",
          rate: "4",
          score: "۸۱",
          isLiked: false,
        },
        {
          id: "9",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-9.jpg",
          title: "ماست بادمجان",
          detail: "بادمجان کبابی، ماست چکیده، سیر، گردو، فلفل سیاه",
          main_price: "۸۰٬۰۰۰",
          discount: "%۸",
          price: "۷۳٬۶۰۰",
          rate: "5",
          score: "۸۶",
          isLiked: false,
        },
        {
          id: "10",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-10.jpg",
          title: "زیتون ساده",
          detail: "زیتون سبز خالص بدون افزودنی",
          main_price: "",
          discount: "",
          price: "۶۰٬۰۰۰",
          rate: "2",
          score: "۵۵",
          isLiked: false,
        },
        {
          id: "11",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-11.jpg",
          title: "سبزی خوردن تازه",
          detail: "ریحان، تره، شاهی، تربچه، پیازچه",
          main_price: "۵۰٬۰۰۰",
          discount: "%۱۰",
          price: "۴۵٬۰۰۰",
          rate: "4",
          score: "۷۰",
          isLiked: false,
        },
        {
          id: "12",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/p-a-12.jpg",
          title: "سوپ جو",
          detail: "جو پرک، هویج، جعفری، شیر، خامه",
          main_price: "۱۴۵٬۰۰۰",
          discount: "%۲۰",
          price: "۱۱۶٬۰۰۰",
          rate: "5",
          score: "۹۵",
          isLiked: false,
        },
      ],
      foreign_appetizers: [
        {
          id: "13",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-1.jpg",
          title: "بروشتای ایتالیایی",
          detail: "نان تست، گوجه فرنگی، سیر، روغن زیتون، ریحان تازه",
          main_price: "۱۴۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۱۹٬۰۰۰",
          rate: "5",
          score: "۸۹",
          isLiked: false,
        },
        {
          id: "14",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-2.jpg",
          title: "سالاد سزار",
          detail: "کاهو رومی، نان کروتان، مرغ گریل‌شده، سس مخصوص سزار، پارمزان",
          main_price: "۲۱۰٬۰۰۰",
          discount: "%۲۰",
          price: "۱۶۸٬۰۰۰",
          rate: "5",
          score: "۹۴",
          isLiked: false,
        },
        {
          id: "15",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-3.jpg",
          title: "حمص لبنانی",
          detail: "نخود پخته، ارده، روغن زیتون، سیر، آب‌لیمو",
          main_price: "۱۱۰٬۰۰۰",
          discount: "%۱۰",
          price: "۹۹٬۰۰۰",
          rate: "4",
          score: "۷۶",
          isLiked: false,
        },
        {
          id: "16",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-4.jpg",
          title: "سالاد یونانی",
          detail: "خیار، گوجه، پنیر فتا، زیتون سیاه، پیاز قرمز، روغن زیتون",
          main_price: "۱۸۰٬۰۰۰",
          discount: "%۵",
          price: "۱۷۱٬۰۰۰",
          rate: "5",
          score: "۸۲",
          isLiked: false,
        },
        {
          id: "17",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-5.jpg",
          title: "پیتزا رول مینی",
          detail: "خمیر پیتزا، سس گوجه، پنیر موزارلا، پپرونی، ریحان خشک",
          main_price: "۱۹۰٬۰۰۰",
          discount: "%۱۸",
          price: "۱۵۶٬۰۰۰",
          rate: "4",
          score: "۸۵",
          isLiked: false,
        },
        {
          id: "18",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-6.jpg",
          title: "سیب‌زمینی فرانسوی",
          detail: "سیب‌زمینی سرخ‌کرده، پنیر چدار، سس مخصوص تارتار و فلفل سیاه",
          main_price: "۱۲۰٬۰۰۰",
          discount: "%۱۰",
          price: "۱۰۸٬۰۰۰",
          rate: "3",
          score: "۶۸",
          isLiked: false,
        },
        {
          id: "19",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-7.jpg",
          title: "چیپس ناچو با پنیر",
          detail: "چیپس ذرت، پنیر چدار، سس سالسا، فلفل هالاپینو",
          main_price: "۱۶۵٬۰۰۰",
          discount: "%۱۲",
          price: "۱۴۵٬۰۰۰",
          rate: "5",
          score: "۹۰",
          isLiked: false,
        },
        {
          id: "20",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-8.jpg",
          title: "بوفالو وینگز",
          detail: "بال مرغ سرخ‌شده، سس تند با کره، چاشنی سیر و سرکه",
          main_price: "۲۳۰٬۰۰۰",
          discount: "%۲۵",
          price: "۱۷۲٬۰۰۰",
          rate: "5",
          score: "۹۳",
          isLiked: false,
        },
        {
          id: "21",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-9.jpg",
          title: "مرینیت زیتون و پنیر",
          detail:
            "زیتون سبز و سیاه، پنیر فتا، رزماری، روغن زیتون، فلفل قرمز خشک",
          main_price: "۱۳۰٬۰۰۰",
          discount: "%۸",
          price: "۱۱۹٬۰۰۰",
          rate: "4",
          score: "۷۹",
          isLiked: false,
        },
        {
          id: "22",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-a-10.jpg",
          title: "قارچ سوخاری",
          detail: "قارچ تازه، پودر سوخاری، تخم مرغ، ادویه مخصوص، سس تارتار",
          main_price: "۱۵۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۲۷٬۵۰۰",
          rate: "4",
          score: "۸۴",
          isLiked: false,
        },
      ],
      soups: [
        {
          id: "23",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/s-1.jpg",
          title: "سوپ جو مخصوص",
          detail:
            "جو پرک، مرغ ریش‌شده، هویج، خامه، شیر، سبزیجات معطر و فلفل سیاه",
          main_price: "۱۲۰٬۰۰۰",
          discount: "%۱۰",
          price: "۱۰۸٬۰۰۰",
          rate: "5",
          score: "۸۴",
          isLiked: false,
        },
        {
          id: "24",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/s-2.jpg",
          title: "سوپ قارچ و مرغ",
          detail: "قارچ تازه، مرغ، خامه، پیاز، فلفل سفید، روغن زیتون، آب مرغ",
          main_price: "۱۱۵٬۰۰۰",
          discount: "%۱۲",
          price: "۱۰۱٬۰۰۰",
          rate: "4",
          score: "۷۸",
          isLiked: false,
        },
        {
          id: "25",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/s-3.jpg",
          title: "سوپ سبزیجات",
          detail:
            "هویج، سیب زمینی، کرفس، ذرت، نخود فرنگی، گوجه فرنگی، روغن زیتون",
          main_price: "۱۰۰٬۰۰۰",
          discount: "%۵",
          price: "۹۵٬۰۰۰",
          rate: "4",
          score: "۶۹",
          isLiked: false,
        },
        {
          id: "26",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/s-4.jpg",
          title: "سوپ گوجه فرنگی",
          detail: "گوجه تازه، ریحان، پیاز، سیر، کره، فلفل سیاه، عصاره سبزیجات",
          main_price: "۹۵٬۰۰۰",
          discount: "",
          price: "۹۵٬۰۰۰",
          rate: "3",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "27",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/s-5.jpg",
          title: "سوپ عدس",
          detail: "عدس قرمز، هویج، سیب زمینی، رب گوجه، ادویه کاری و آب سبزیجات",
          main_price: "۱۱۰٬۰۰۰",
          discount: "%۸",
          price: "۱۰۱٬۰۰۰",
          rate: "5",
          score: "۸۹",
          isLiked: false,
        },
        {
          id: "28",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/s-6.jpg",
          title: "سوپ ترخینه سنتی",
          detail:
            "ترخینه خشک، دوغ، سبزیجات معطر، پیاز داغ، سیر، فلفل قرمز و نعناع خشک",
          main_price: "۱۳۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۱۰٬۵۰۰",
          rate: "5",
          score: "۹۳",
          isLiked: false,
        },
      ],
      finger_foods: [
        {
          id: "29",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-f-1.jpg",
          title: "هات‌داگ مخصوص ترخینه",
          detail:
            "هات‌داگ دودی، پنیر گودا، خیارشور، سس مخصوص، پیاز کاراملی و نان تست شده",
          main_price: "۲۳۰٬۰۰۰",
          discount: "%۲۰",
          price: "۱۸۴٬۰۰۰",
          rate: "5",
          score: "۸۸",
          isLiked: true,
        },
        {
          id: "30",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-f-2.jpg",
          title: "سیب‌زمینی با پنیر و بیکن",
          detail:
            "سیب‌زمینی سرخ‌شده، پنیر چدار، بیکن گیاهی، پیازچه، فلفل سیاه و سس مخصوص",
          main_price: "۱۸۵٬۰۰۰",
          discount: "%۱۵",
          price: "۱۵۷٬۰۰۰",
          rate: "4",
          score: "۷۶",
          isLiked: false,
        },
        {
          id: "31",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-f-3.jpg",
          title: "ناگت سبزیجات",
          detail:
            "سیب‌زمینی، هویج، نخود فرنگی، ذرت، فلفل دلمه‌ای، پودر سوخاری و ادویه مخصوص",
          main_price: "۱۶۰٬۰۰۰",
          discount: "%۱۰",
          price: "۱۴۴٬۰۰۰",
          rate: "3",
          score: "۶۴",
          isLiked: false,
        },
        {
          id: "32",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/appetizer/f-f-4.jpg",
          title: "اسپرینگ رول سبزیجات",
          detail:
            "کلم، هویج، فلفل دلمه‌ای، نودل برنج، سس سویا و زنجبیل تازه، رول شده در خمیر مخصوص",
          main_price: "۱۹۵٬۰۰۰",
          discount: "%۱۸",
          price: "۱۶۰٬۰۰۰",
          rate: "5",
          score: "۹۲",
          isLiked: true,
        },
      ],
    },
    {
      id: 3,
      name: "dessert",
      persian_desserts: [
        {
          id: "2",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/p-d-1.jpg",
          title: "شیرینی قطاب",
          detail: "آرد، گردو، هل، شکر، طعم سنتی و خوشمزه",
          main_price: "۹۵٬۰۰۰",
          discount: "%۱۵",
          price: "۸۰٬۷۵۰",
          rate: "4",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "3",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/p-d-2.jpg",
          title: "سوهان",
          detail: "شکر، کره، زعفران، خلال پسته، طعم اصیل ایرانی",
          main_price: "۱۱۰٬۰۰۰",
          discount: "%۱۲",
          price: "۹۶٬۸۰۰",
          rate: "5",
          score: "۸۹",
          isLiked: false,
        },
        {
          id: "4",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/p-d-3.jpg",
          title: "باقلوا",
          detail: "خمیر فیلو، گردو، شربت شیرین، طعم سنتی و دلپذیر",
          main_price: "۱۳۰٬۰۰۰",
          discount: "%۲۰",
          price: "۱۰۴٬۰۰۰",
          rate: "5",
          score: "۹۲",
          isLiked: false,
        },
        {
          id: "7",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/p-d-4.jpg",
          title: "فرنی با گلاب",
          detail: "آرد برنج، شیر، شکر، گلاب، طعمی ملایم و سنتی",
          main_price: "۷۵٬۰۰۰",
          discount: "%۱۰",
          price: "۶۷٬۵۰۰",
          rate: "5",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "9",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/p-d-5.jpg",
          title: "گلابی پخته با شکر",
          detail: "گلابی تازه، شکر، دارچین، طعم ملایم و سنتی",
          main_price: "۹۰٬۰۰۰",
          discount: "%۱۰",
          price: "۸۱٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "10",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/p-d-6.jpg",
          title: "کیک یزدی",
          detail: "آرد، شکر، تخم مرغ، روغن، طعم سنتی و سبک",
          main_price: "۸۵٬۰۰۰",
          discount: "%۵",
          price: "۸۰٬۷۵۰",
          rate: "4",
          score: "۶۹",
          isLiked: false,
        },
      ],
      foreign_desserts: [
        {
          id: "11",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/f-d-1.jpg",
          title: "چیزکیک نیویورکی",
          detail: "پنیر خامه‌ای، بیسکوییت، کره، سس توت فرنگی",
          main_price: "۲۳۰٬۰۰۰",
          discount: "%۲۰",
          price: "۱۸۴٬۰۰۰",
          rate: "5",
          score: "۹۰",
          isLiked: false,
        },
        {
          id: "12",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/f-d-2.jpg",
          title: "پودینگ شکلاتی",
          detail: "شکلات تلخ، شیر، شکر، خامه، طعمی غلیظ و دلچسب",
          main_price: "۲۰۵٬۰۰۰",
          discount: "%۱۵",
          price: "۱۷۴٬۲۵۰",
          rate: "5",
          score: "۸۴",
          isLiked: false,
        },
        {
          id: "13",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/f-d-3.jpg",
          title: "تیرامیسو",
          detail: "کیک اسفنجی، ماسکارپونه، قهوه، کاکائو",
          main_price: "۲۲۰٬۰۰۰",
          discount: "%۱۰",
          price: "۱۹۸٬۰۰۰",
          rate: "5",
          score: "۸۷",
          isLiked: false,
        },
        {
          id: "14",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/f-d-4.jpg",
          title: "پاناکوتا",
          detail: "خامه، ژلاتین، شکر، سس توت فرنگی",
          main_price: "۱۸۵٬۰۰۰",
          discount: "%۱۵",
          price: "۱۵۷٬۲۵۰",
          rate: "4",
          score: "۷۹",
          isLiked: false,
        },
        {
          id: "15",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/f-d-5.jpg",
          title: "کراست پودینگ",
          detail: "نان، شیر، شکر، کشمش، طعم سنتی انگلیسی",
          main_price: "۱۷۵٬۰۰۰",
          discount: "%۱۰",
          price: "۱۵۷٬۵۰۰",
          rate: "4",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "16",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/f-d-6.jpg",
          title: "موس شکلاتی",
          detail: "شکلات تلخ، تخم مرغ، شکر، خامه، طعمی سبک و مطبوع",
          main_price: "۱۹۰٬۰۰۰",
          discount: "%۱۲",
          price: "۱۶۷٬۲۰۰",
          rate: "5",
          score: "۸۳",
          isLiked: false,
        },
        {
          id: "17",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/f-d-7.jpg",
          title: "کرم کارامل",
          detail: "شیر، تخم مرغ، شکر، وانیل، طعم کلاسیک فرانسوی",
          main_price: "۱۷۰٬۰۰۰",
          discount: "%۱۰",
          price: "۱۵۳٬۰۰۰",
          rate: "4",
          score: "۷۶",
          isLiked: false,
        },
        {
          id: "18",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/f-d-8.jpg",
          title: "مادلن فرانسوی",
          detail: "آرد، شکر، تخم مرغ، کره، طعمی سبک و خوشبو",
          main_price: "۱۸۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۵۳٬۰۰۰",
          rate: "4",
          score: "۸۰",
          isLiked: false,
        },
      ],
      jellies: [
        {
          id: "19",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/j-1.jpg",
          title: "ژله توت فرنگی",
          detail: "پودر ژله، شکر، آب، طعمی ملایم و شیرین",
          main_price: "۷۵٬۰۰۰",
          discount: "%۱۰",
          price: "۶۷٬۵۰۰",
          rate: "5",
          score: "۶۸",
          isLiked: false,
        },
        {
          id: "20",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/j-2.jpg",
          title: "ژله آناناس",
          detail: "ژله آناناس، شکر، آب، طعم شیرین و ترش",
          main_price: "۸۰٬۰۰۰",
          discount: "%۵",
          price: "۷۶٬۰۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "21",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/j-3.jpg",
          title: "ژله آلبالو",
          detail: "ژله آلبالو، شکر، آب، طعم ملس و خوشمزه",
          main_price: "۷۸٬۰۰۰",
          discount: "%۸",
          price: "۷۱٬۷۰۰",
          rate: "4",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "22",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/j-4.jpg",
          title: "ژله پرتقال",
          detail: "ژله پرتقال، شکر، آب، طعم تازه و خوشایند",
          main_price: "۷۵٬۰۰۰",
          discount: "",
          price: "۷۵٬۰۰۰",
          rate: "5",
          score: "۶۹",
          isLiked: false,
        },
      ],
      cakes: [
        {
          id: "23",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/c-1.jpg",
          title: "کیک شکلاتی",
          detail: "آرد، شکر، تخم مرغ، کره، شکلات تلخ، خامه",
          main_price: "۲۲۰٬۰۰۰",
          discount: "%۱۵",
          price: "۱۸۷٬۰۰۰",
          rate: "5",
          score: "۹۲",
          isLiked: false,
        },
        {
          id: "24",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/c-2.jpg",
          title: "کیک وانیلی",
          detail: "آرد، شکر، تخم مرغ، کره، وانیل، خامه",
          main_price: "۲۰۰٬۰۰۰",
          discount: "%۱۰",
          price: "۱۸۰٬۰۰۰",
          rate: "4",
          score: "۸۴",
          isLiked: false,
        },
        {
          id: "25",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/c-3.jpg",
          title: "کیک کاراملی",
          detail: "آرد، شکر، کره، کارامل، تخم مرغ، طعمی شیرین و خوشبو",
          main_price: "۲۱۰٬۰۰۰",
          discount: "%۱۲",
          price: "۱۸۴٬۸۰۰",
          rate: "5",
          score: "۸۹",
          isLiked: false,
        },
        {
          id: "26",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/dessert/c-4.jpg",
          title: "کیک میوه‌ای",
          detail: "آرد، شکر، تخم مرغ، کره، میوه‌های تازه، خامه",
          main_price: "۲۳۰٬۰۰۰",
          discount: "%۱۸",
          price: "۱۸۸٬۶۰۰",
          rate: "4",
          score: "۸۰",
          isLiked: false,
        },
      ],
    },
    {
      id: 4,
      name: "drink",
      persian_drinks: [
        {
          id: "1",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/p-d-1.jpg",
          title: "دوغ سنتی",
          detail: "دوغ، نعناع خشک، کمی نمک، طعمی خنک و سنتی",
          main_price: "۳۰٬۰۰۰",
          discount: "%۱۰",
          price: "۲۷٬۰۰۰",
          rate: "5",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "2",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/p-d-2.jpg",
          title: "عرق نعناع",
          detail: "عرق نعناع طبیعی، طعم خنک و خوشبو",
          main_price: "۲۵٬۰۰۰",
          discount: "",
          price: "۲۵٬۰۰۰",
          rate: "4",
          score: "۷۰",
          isLiked: false,
        },
        {
          id: "3",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/p-d-3.jpg",
          title: "شربت زعفران",
          detail: "زعفران، شکر، آب، کمی لیمو، طعم شیرین و دلپذیر",
          main_price: "۴۰٬۰۰۰",
          discount: "%۱۵",
          price: "۳۴٬۰۰۰",
          rate: "5",
          score: "۸۰",
          isLiked: false,
        },
        {
          id: "4",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/p-d-4.jpg",
          title: "شربت سکنجبین",
          detail: "سکنجبین، عسل، طعم ترش و شیرین طبیعی",
          main_price: "۳۵٬۰۰۰",
          discount: "%۱۰",
          price: "۳۱٬۵۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "5",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/p-d-5.jpg",
          title: "شربت آلبالو",
          detail: "آلبالو، شکر، آب، طعمی ملس و خوشمزه",
          main_price: "۳۵٬۰۰۰",
          discount: "%۵",
          price: "۳۳٬۲۵۰",
          rate: "5",
          score: "۷۸",
          isLiked: false,
        },
        {
          id: "6",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/p-d-6.jpg",
          title: "شربت به لیمو",
          detail: "به، لیمو، شکر، طعمی تازه و خوشایند",
          main_price: "۳۸٬۰۰۰",
          discount: "%۱۰",
          price: "۳۴٬۲۰۰",
          rate: "4",
          score: "۷۳",
          isLiked: false,
        },
        {
          id: "7",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/p-d-7.jpg",
          title: "سرویس چای سنتی",
          detail: "چای سیاه، هل، دارچین، طعمی گرم و دلنشین",
          main_price: "۲۰٬۰۰۰",
          discount: "",
          price: "۲۰٬۰۰۰",
          rate: "5",
          score: "۷۰",
          isLiked: false,
        },
        {
          id: "8",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/p-d-8.jpg",
          title: "شربت لیمو",
          detail: "آبلیمو، شکر، نعناع خشک، طعمی خنک و تازه",
          main_price: "۳۰٬۰۰۰",
          discount: "%۱۰",
          price: "۲۷٬۰۰۰",
          rate: "4",
          score: "۷۵",
          isLiked: false,
        },
      ],
      foreign_drinks: [
        {
          id: "9",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/f-d-1.jpg",
          title: "لیموناد کلاسیک",
          detail: "آبلیمو، شکر، آب، طعمی خنک و تازه",
          main_price: "۳۵٬۰۰۰",
          discount: "%۱۰",
          price: "۳۱٬۵۰۰",
          rate: "5",
          score: "۸۰",
          isLiked: false,
        },
        {
          id: "10",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/f-d-2.jpg",
          title: "آب پرتقال تازه",
          detail: "پرتقال تازه، طبیعی و بدون افزودنی",
          main_price: "۳۵٬۰۰۰",
          discount: "",
          price: "۳۵٬۰۰۰",
          rate: "4",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "11",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/f-d-3.jpg",
          title: "شیک شکلات",
          detail: "شیر، شکلات، خامه، طعمی غنی و خوشمزه",
          main_price: "۴۵٬۰۰۰",
          discount: "%۱۵",
          price: "۳۸٬۲۵۰",
          rate: "5",
          score: "۸۵",
          isLiked: false,
        },
        {
          id: "12",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/f-d-4.jpg",
          title: "شیک وانیلی",
          detail: "شیر، وانیل، شکر، خامه، طعمی ملایم و خوشبو",
          main_price: "۴۰٬۰۰۰",
          discount: "%۱۰",
          price: "۳۶٬۰۰۰",
          rate: "4",
          score: "۷۸",
          isLiked: false,
        },
        {
          id: "13",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/f-d-5.jpg",
          title: "آیس تی لیمو",
          detail: "چای سیاه، آبلیمو، شکر، یخ، طعمی خنک و تازه",
          main_price: "۳۰٬۰۰۰",
          discount: "%۵",
          price: "۲۸٬۵۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "14",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/f-d-6.jpg",
          title: "موهیتو",
          detail: "نعناع تازه، شکر، آبلیمو، سودا، طعمی خنک و جذاب",
          main_price: "۴۰٬۰۰۰",
          discount: "%۱۰",
          price: "۳۶٬۰۰۰",
          rate: "5",
          score: "۸۲",
          isLiked: false,
        },
      ],
      cold_drinks: [
        {
          id: "15",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/c-d-1.jpg",
          title: "آب سیب طبیعی",
          detail: "سیب تازه، طبیعی و بدون افزودنی",
          main_price: "۳۰٬۰۰۰",
          discount: "%۵",
          price: "۲۸٬۵۰۰",
          rate: "5",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "16",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/c-d-2.jpg?v=2",
          title: "نوشابه",
          detail: "کولا، گازدار و خنک",
          main_price: "۲۰٬۰۰۰",
          discount: "",
          price: "۲۰٬۰۰۰",
          rate: "4",
          score: "۷۰",
          isLiked: false,
        },
        {
          id: "17",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/c-d-3.jpg",
          title: "دلستر",
          detail: "ماءالشعیر بدون الکل، طعمی شیرین و خنک",
          main_price: "۲۵٬۰۰۰",
          discount: "%۱۰",
          price: "۲۲٬۵۰۰",
          rate: "4",
          score: "۷۲",
          isLiked: false,
        },
        {
          id: "18",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/c-d-4.jpg",
          title: "آب هندوانه",
          detail: "هندوانه تازه، طبیعی و خنک",
          main_price: "۳۰٬۰۰۰",
          discount: "",
          price: "۳۰٬۰۰۰",
          rate: "5",
          score: "۷۸",
          isLiked: false,
        },
      ],
      hot_drinks: [
        {
          id: "19",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/h-d-1.jpg",
          title: "چای سیاه",
          detail: "چای سیاه خالص، طعمی گرم و دلنشین",
          main_price: "۲۰٬۰۰۰",
          discount: "",
          price: "۲۰٬۰۰۰",
          rate: "5",
          score: "۷۵",
          isLiked: false,
        },
        {
          id: "20",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/h-d-2.jpg",
          title: "چای سبز",
          detail: "چای سبز خالص، آرامش‌بخش و مفید",
          main_price: "۲۰٬۰۰۰",
          discount: "",
          price: "۲۰٬۰۰۰",
          rate: "4",
          score: "۷۰",
          isLiked: false,
        },
        {
          id: "21",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/h-d-3.jpg",
          title: "قهوه اسپرسو",
          detail: "قهوه خالص، طعمی غلیظ و قوی",
          main_price: "۳۵٬۰۰۰",
          discount: "%۱۰",
          price: "۳۱٬۵۰۰",
          rate: "5",
          score: "۸۰",
          isLiked: false,
        },
        {
          id: "22",
          image:
            "https://raw.githubusercontent.com/mahdi-q/Tarkhineh-App-API/refs/heads/master/images/menu/drink/h-d-4.jpg",
          title: "چای ماسالا",
          detail: "چای سیاه، ادویه ماسالا، شیر، طعمی گرم و معطر",
          main_price: "۳۵٬۰۰۰",
          discount: "%۵",
          price: "۳۳٬۲۵۰",
          rate: "4",
          score: "۷۵",
          isLiked: false,
        },
      ],
    },
  ],
};

// Use jsonServer.router with the embedded database object
const router = jsonServer.router(db);
const middlewares = jsonServer.defaults();

server.use(middlewares);
server.use(jsonServer.bodyParser);

// Rewrite paths if necessary
server.use(
  jsonServer.rewriter({
    "/api/*": "/$1",
    "/blog/:resource/:id/show": "/:resource/:id",
  })
);

server.use((req, res, next) => {
  if (["POST", "PUT", "PATCH", "DELETE"].includes(req.method)) {
    router.db.setState(db); // Reset state for any modification
  }
  next();
});

// Start the JSON server
server.use(router);
server.listen(3000, () => {
  console.log("JSON Server is running on http://localhost:3000");
});

module.exports = server;
